# Starkit support, see http://www.equi4.com/starkit/
# by Jean-Claude Wippler, July 2002

# Starkit scripts can launched in a number of ways:
#   - wrapped or unwrapped
#   - using tclkit, or from tclsh/wish with a couple of pkgs installed
#   - with real MetaKit support, or with a read-only fake (ReadKit)
#   - as 2-file starkit deployment, or as 1-file starpack
#
# Furthermore, there are four variations:
#   future:   starkits using zip, for tclkit using zipfs (THIS WORK, v2.0.0)
#   current:  starkits
#   older:    VFS-based "scripted documents"
#   oldest:   pre-VFS "scripted documents"
#
# The code in here is only called directly from the current starkits.

# Earlier versions of Tcl must use starkit v1.
package require tcl 9

namespace eval starkit {
    # these variables are defined after the call to starkit::startup
    # they are special in that a second call will not alter them
    # (as needed when a starkit sources others for more packages)
    variable topdir	;# root directory (while the starkit is mounted)
    variable mode 	;# startup mode (starkit, sourced, etc)

    # Not special.  Used by each call to starkit::startup.
    variable TmpDirs {}	;# clean these up on exit

    # called from the header of a starkit
    proc header {driver args} {
	if {[catch {
	    set self [fullnormalize [info script]]
	    if {$driver eq {zip}} {
		# New starkit using zipfs; or old starkit using vfs::zip.
		set mountpoint [zipfs mount $self [file join [zipfs root] starkit]]
		uplevel [list source [file join $mountpoint main.tcl]]
	    } elseif {$driver eq {mk4}} {
		# Old starkit based on TclVFS with metakit or vlerq.
		package require vfs
		package require vfs::${driver}
		# Code to unpack the starkit.
		# eval [list ::vfs::${driver}::Mount $self $self] $args
		set topDir [UnpackOldKit $self]
		# Source the starkit from its unpacked location.
		uplevel [list source [file join $topDir main.tcl]]
	    } else {
		panic "format \"$driver\" is not supported"
	    }
	}]} {
	    panic $::errorInfo
	}
    }

    # Command to unpack a TclVFS starkit from $path and write its files to a
    # temporary location.
    # - Unpacked files are preferable to building and mounting a zipkit.
    # - Also FIXME a readkit bug: a Tcl file in a zip files generated by
    #   readkit -z and mounted with zipfs cannot be [source]d.
    proc UnpackOldKit {kitPath} {
        global argv
        variable TmpDirs

        set newDir [file tempdir]
        lappend TmpDirs $newDir

        if {[info commands ::__ekh__exit] eq {}} {
            rename ::exit ::__ekh__exit
            rename ::starkit::ExitKitHook ::exit
        }

        set oldPwd [pwd]
        set argvold $argv

        cd $newDir
        set argv [list -x $kitPath]
        package require readkit
        # The package file is still an executable script,
        # and it writes filenames to stdout.
        # FIXME readkit operations can be exposed as commands to make this neater.
        set argv $argvold
        cd $oldPwd

        # This should be the base directory created by readkit.
        set dirName [file join $newDir [file rootname [file tail $kitPath]].vfs]

        if {![file isdirectory $dirName]} {
            panic "unpacked directory not at the expected location \"$dirName\""
        }
        return $dirName
    }

    # Clean up any temporary directories created for unpacked starkits.
    # Test that they are in the temporary-file location.
    # Always exit.
    proc ExitKitHook {args} {
        variable ::starkit::TmpDirs

        catch {
            set newDir [file tempdir]
            lappend TmpDirs $newDir
            set TmpBase [file dirname $newDir]

            foreach dir $::starkit::TmpDirs {
                if {[file exists $dir] && ([file dirname $dir] eq $TmpBase)} {
                    file delete -force $dir
                }
            }
        }
        uplevel 1 ::__ekh__exit $args
    }

    proc fullnormalize {path} {
	# SNARFED from tcllib, fileutil.
	# 8.5
	# return [file join {expand}[lrange [file split
	#    [file normalize [file join $path __dummy__]]] 0 end-1]]

	return [file dirname [file normalize [file join $path __dummy__]]]
    }

    # called from the startup script of a starkit to init topdir and auto_path
    # 2003/10/21, added in 1.3: remember startup mode in starkit::mode
    proc startup {} {
	if {![info exists starkit::mode]} { variable mode }

	set script [fullnormalize [info script]]
	set topDir [file dirname $script]
	set root   [zipfs root]
	set zfslen [string length $root]
	if {[string range $topDir 0 $zfslen-1] eq [zipfs root]} {
	    set mode [_startup9]
	} else {
	    set mode [_startup8]
	}
	return $mode
    }

    # returns how the script was launched: starkit, starpack, unwrapped, or
    # sourced (2003: also tclhttpd, plugin, or service)
    proc _startup9 {} {
	global argv0

	# 2003/02/11: new behavior, if starkit::topdir exists, don't disturb it
	if {![info exists starkit::topdir]} { variable topdir }

	set script [fullnormalize [info script]]
	set topdir [file dirname $script]
	set root   [zipfs root]
	set zfslen [string length $root]

	if {    [fullnormalize [zipfs mount $topdir]]
	     eq [fullnormalize [info nameofexe]]
	} {
	    return starpack
	}

	# pkgs live in the $topdir/lib/ directory
	set lib [file join $topdir lib]
	if {[file isdir $lib]} { autoextend $lib withTM }

	set a0 [fullnormalize $argv0]
	if {[string range $topdir 0 $zfslen-1] eq [zipfs root]} {
	    return starkit
	}
	if {$script eq $a0} { return unwrapped }

	# detect when sourced from tclhttpd
	if {[info procs ::Httpd_Server] ne ""} { return tclhttpd }

	# detect when sourced from the plugin (tentative)
	if {[info exists ::embed_args]} { return plugin }

	# detect when run as an NT service
	if {[info exists ::tcl_service]} { return service }
	return sourced
    }


    # returns how the script was launched: starkit, starpack, unwrapped, or
    # sourced (2003: also tclhttpd, plugin, or service)
    proc _startup8 {} {
	global argv0

	# 2003/02/11: new behavior, if starkit::topdir exists, don't disturb it
	if {![info exists starkit::topdir]} { variable topdir }

	set script [fullnormalize [info script]]
	set topdir [file dirname $script]

	if {$topdir eq [fullnormalize [info nameofexe]]} { return starpack }

	# pkgs live in the $topdir/lib/ directory
	set lib [file join $topdir lib]
	if {[file isdir $lib]} { autoextend $lib }

	set a0 [fullnormalize $argv0]
	if {$topdir eq $a0} { return starkit }
	if {$script eq $a0} { return unwrapped }

	# detect when sourced from tclhttpd
	if {[info procs ::Httpd_Server] ne ""} { return tclhttpd }

	# detect when sourced from the plugin (tentative)
	if {[info exists ::embed_args]} { return plugin }

	# detect when run as an NT service
	if {[info exists ::tcl_service]} { return service }

	return sourced
    }

    # append an entry to auto_path if it's not yet listed
    # also module paths if requested by ($withTm ne {})
    proc autoextend {dir {withTm {}}} {
	global auto_path
	set dir [fullnormalize $dir]
	if {[lsearch $auto_path $dir] < 0} {
	    lappend auto_path $dir
	}
	if {$withTm eq {}} { return }
	set dlen [string length $dir]
	foreach path [tcl::tm::list] {
	    if {[string range [fullnormalize $path] 0 $dlen-1] eq $dir} {
		return
	    }
	}
	lassign [split $::tcl_version .] major
	if {[file isdirectory [file join $dir tcl$major]]} {
	    tcl::tm::roots $dir
	}
	return
    }

    # remount a starkit with different options
    proc remount {args} {
	variable topdir
	foreach {drv arg} [vfs::filesystem info $topdir] { break }
	vfs::unmount $topdir

	eval [list [string map {handler Mount} $drv] $topdir $topdir] $args
    }

    # terminate with an error message, using most appropriate mechanism
    proc panic {msg} {
	if {[info commands wm] ne ""} {
	    catch { wm withdraw . }
	    tk_messageBox -icon error -message $msg -title "Fatal error"
	} elseif {[info commands ::eventlog] ne ""} {
	    eventlog error $msg
	} else {
	    puts stderr $msg
	}
	exit
    }

    # the following proc was copied from the critcl package:

    # return a platform designator, including both OS and machine
    #
    # only use first element of $tcl_platform(os) - we don't care
    # whether we are on "Windows NT" or "Windows XP" or whatever
    #
    # transforms $tcl_platform(machine) for some special cases
    #  - on SunOS, matches for sun4* are transformed to sparc
    #  - on all OS's matches for intel and i*86* are transformed to x86
    #  - on MacOS X "Power Macintosh" is transformed to ppc
    #
    proc platform {} {
        global tcl_platform
        set plat [lindex $tcl_platform(os) 0]
        set mach $tcl_platform(machine)
        switch -glob -- $mach {
            sun4* { set mach sparc }
            intel -
            i*86* { set mach x86 }
            "Power Macintosh" { set mach ppc }
        }
	switch -- $plat {
	  AIX   { set mach ppc }
	  HP-UX { set mach hppa }
	}
        return "$plat-$mach"
    }

    # load extension from a platform-specific subdirectory
    proc pload {dir name args} {
      set f [file join $dir [platform] $name[info sharedlibext]]
      uplevel 1 [linsert $args 0 load $f]
    }
}

package provide starkit 2.0.0

